version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: e-commerce-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/common_postgres:/data/db

